#!/bin/bash

names='FirstName;LastName;UserName;CompleteName;Email;Group 
FirstName;LastName;UserName;CompleteName;Email;Group'

export IFS=";"

while read first last username completeName email group
do
        echo "ipa user-find --email=${email}"
        echo "ipa user-add ${username} --first=${first} --last=${last} --email=${email} --shell=/bin/csh --cn=${completeName} --groups=${group} --password"
#       echo "ipa group-add-member GROUP-NAME --users=${username}"
done <<<"$names"

